### ISSUE TITLE
Why the namenode needs to install zkfc ?

### ISSUE THREAD

**Issue by IDerr** [ryba-io/ryba#101]
Hi,
I am trying to install ryba standalone but, the namenode tries to install zkfc, but zkfc needs at least two hosts to be installled. It would be better if we install it as standalone module ?

https://github.com/ryba-io/ryba/blame/master/hadoop/hdfs_nn/index.coffee.md#L35-L36

**Comment by wdavidw** [comment]
zkfc is meant to supervised namenodes to make sure they dont get into a split brain scenario. thus, this involve two namenodes, which meant zkfc is specific to HA. In standalone, you have no HA and you'll have to re-birth the hdfs_snn service for a recommanded installation.

**Comment by wdavidw** [comment]
Note, in the migration branch, I have blindly upgrade the hdfs_snn service so even if it probably doesnt work, it shall be close to be migrated.

**Comment by IDerr** [comment]
Ok, so snn means "standalone namenode" right ?  

I'll try with that, and will close the issue, if it works.

Thanks :)

**Comment by IDerr** [comment]
Secondary namenode.

**Comment by lucasbak** [comment]
Nope, snn stands for Secondary NameNode, its a namenode which only share a copye of the FsImage as a backup, but can not be online and active.
