### ISSUE TITLE
Ambari Views

### ISSUE THREAD

**Issue by Pierrotws** [ryba-io/ryba#14]

**Comment by IDerr** [comment]
I think @lucasbak has nearly finished this module

**Comment by wdavidw** [comment]
@lucasbak is this right, can we close or do you wish to add a few things ? On my side, i'll consider the service finish when it land inside ryba-env-metal

**Comment by IDerr** [comment]
I agree, when he'll push the code on env-metal, I'll close this

**Comment by IDerr** [comment]
f3e46a9e37165ebcabd252ccb70472f9570d3f9c

We can close :)

**Comment by lucasbak** [comment]
Yep the example one configuration is already in env-metal since last Friday, it is commented though.

**Comment by wdavidw** [comment]
great, must be activated if ready
