### ISSUE TITLE
Zookeeper auth_to_local

### ISSUE THREAD

**Issue by Pierrotws** [ryba-io/ryba#47]
Insert in zookeeper-en.sh 
SERVER_JVMFLAGS="[...] -Dzookeeper.security.auth_to_local=RULE:[...]RULE:[... ]"

two problems right now :
- For now, auth_to_local is defined in core-site, should be defined elsewhere, since it's no more hadoop_specific
- as this rule is written in bash script, must be properly escaped.

**Comment by Pierrotws** [comment]
Even correctly escaped, this cannot be achieved as hdfs is assuming that zookeeper honors default rules.

Indeed, it will force ACL /hadoop-ha to nn ID, even if this principal is mapping on hdfs.

**Comment by IDerr** [comment]
If it's dead, why not close this issue ? @wdavidw

**Comment by wdavidw** [comment]
I'll leave the decision to @Pierrotws
