### ISSUE TITLE
kafka: Check ACL

### ISSUE THREAD

**Issue by lucasbak** [ryba-io/ryba#57]
Rewrite check to ensure ACL conf is working,
write also a kafka/client instead of using kafka/consumer and kafka/producer as kafkaClient

**Comment by wdavidw** [comment]
not sure I agree with second point. i understand that  install / check are redundant but i like the separation of concern

**Comment by lucasbak** [comment]
I don't wan't to remove the separation. From now we can consider than consumer/producer are kafka Clients. We can write a kafka/client module which does the client's installation layout (jaas, env because they are identical for consumer/producer or any other client) and some checks , and let in the consumer/producer only their part (consumer.properties/producer.properties). This will let the check part of consumer and producer as they are.

**Comment by wdavidw** [comment]
so if client is not consoumer+producer, then what is the role of a client in kafka meaning

**Comment by lucasbak** [comment]
In kafka meaning  a client is only producer/consumer, but in code-development meaning a client is a package not issued from kafka's rpms. That's from this point of view that the issue has been opened, but that's just a proposal. we can let it for now as closed and open it later when needed ?

**Comment by wdavidw** [comment]
Client seems really confusing to me, why not kafka-developer then. In code devopment, u dont need kafka at all because ull receive your dependencie through mvn, npm... Does this client-client idea answer a real demand? If not then lets postpone it

**Comment by lucasbak** [comment]
Agreed, it is not a real demand
