### ISSUE TITLE
Hive password 

### ISSUE THREAD

**Issue by IDerr** [ryba-io/ryba#69]
ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements
ryba/hive/hcatalog Error: DB user does not exists: hive

We should change the default password to meet the requirements, otherwise the account is not created..

**Comment by IDerr** [comment]
Nevermind, mysql from oracle came with the plugin  validate_password 

`uninstall plugin validate_password;`

And It's good

**Comment by wdavidw** [comment]
Default passwords will be progressively removed from masson and ryba in the next few weeks for security reasons.
