### ISSUE TITLE
YARN NM enforcing memory check

### ISSUE THREAD

**Issue by wdavidw** [ryba-io/ryba#70]
On RH7, [Cloudera](http://blog.cloudera.com/blog/2014/04/apache-hadoop-yarn-avoiding-6-time-consuming-gotchas) recommended passing "yarn.nodemanager.vmem-check-enabled" to "false". Now that we are targeting RH7, we shall probably set it to "true" again. Note for backward compatibility, in a heterogenous OS environnement, the property can be defined at a node level in the user configuration. Feel free to discuss this commit.

**Comment by Pierrotws** [comment]
I think you meant "On RHEL **6**, Cloudera [...]. Now that we are targeting RHEL **7**".

Agreed.

**Comment by wdavidw** [comment]
yes, u're right, rh6
