### ISSUE TITLE
pig: hcat check fail because hadoop-env.sh doesnt honors HADOOP_CLIENT_OPTS

### ISSUE THREAD

**Issue by wdavidw** [ryba-io/ryba#74]
The source of the problem lies inside "/etc/hadoop/conf/hadoop-env.sh":

```
export HADOOP_CLIENT_OPTS="-Xmx2048m"
```
which should be

```
export HADOOP_CLIENT_OPTS="-Xmx2048m $HADOOP_CLIENT_OPTS"
```

**Comment by wdavidw** [comment]
Note, user were affected before this patch

**Comment by lucasbak** [comment]
check the lines 86-87 of hadoop-env.sh, they already contain the expressions that you need.
