### ISSUE TITLE
Conf-select conflict when installing zookeeper

### ISSUE THREAD

**Issue by IDerr** [ryba-io/ryba#83]
file /usr/bin/conf-select from install of hdp-select-2.5.5.0-157.el6.noarch conflicts with file from package hdf-select-2.1.2.0-10.el6.noarch

I know that, hdf module takes care of the cohabitation, but I don't know if we should put it as a dependency.

**Comment by wdavidw** [comment]
hortonworks prohibit a co-installation of hdp with hdf, we should not waste a second trying to support it.

**Comment by IDerr** [comment]
Yes I agree :D
