### ISSUE TITLE
Move registry

### ISSUE THREAD

**Issue by wdavidw** [ryba-io/ryba#84]
At a time when i'm thinking about moving all stable components such as openldap and kerberos into ryba, it doesnt seem right to create a top level component for the schema registry. I propose multiple alternative open to discussion:

* move registry into nifi
* move registry into hdf
* move registry into nifi and nifi into hdf

**Comment by lucasbak** [comment]
You should move it to hdf as Hortonworks seems to use it only  for end to end data management.

**Comment by wdavidw** [comment]
@Pierrotws , i'll let you do it, dont forget to add it to to ryba-env-[metal & ambari-hdf] when ready, thanks

**Comment by wdavidw** [comment]
could we move on this one ?

**Comment by wdavidw** [comment]
@Pierrotws this is mostly some refactaring as far as i understand it, we could we move on quicky on this one and close the issue afterward ?

**Comment by wdavidw** [comment]
Thanks, we'll have to cherry pick that one into migration
