### ISSUE TITLE
Help understanding @config.log4j

### ISSUE THREAD

**Issue by wdavidw** [ryba-io/ryba#93]
Global configuration through `@config` behing depracated and soon remove, I'm trying to understand how `@config.log4j` is created and used. Is it managed by a service like the "ssl" or "db_admin" or is it simply a configuration object that anyone is free to pick up information from ? Are there any documentation about it's usage ?

**Comment by wdavidw** [comment]
Could someone provides with an answer, even partial?

**Comment by Pierrotws** [comment]
@lucasbak should confirm but imho it is simply a configuration object where anyone can get/inherits/override configuration. It has been implemented quite a long time ago, on the demand of Damien.
If I had to reimplement it, I would create a true service just like ssl and db_admin.

**Comment by lucasbak** [comment]
+1, exactly what i think

**Comment by wdavidw** [comment]
Then a service should be created, future migration doesnt allow global configuration
