### ISSUE TITLE
migration: questions around ranger hdfs plugins

### ISSUE THREAD

**Issue by wdavidw** [ryba-io/ryba#95]
Two questions for now:

* `config.ryba.hdfs.namenode_opts` in [ranger/plugins/hdfs/configure](https://github.com/ryba-io/ryba/blame/a69144eb51166fabd9f14318ccca47a44fcfb959/ranger/plugins/hdfs/configure.coffee.md#L25-L27)
  I can't find any reference to this options, hdfs_nn only honors `opts`, `hadoop_opts` and `java_opts` (by the way, it seems a bit too much, no ?). However, this seems pretty important as it add SSl tuststore and keystore path definition.
* `ranger.hdfs_plugin.principal` and `ranger.hdfs_plugins.password` in [ranger/plugins/hdfs/setup](https://github.com/ryba-io/ryba/blame/a69144eb51166fabd9f14318ccca47a44fcfb959/ranger/plugins/hdfs/setup.coffee.md#L36-L38)
  I can't find where is this is defined, please help

**Comment by lucasbak** [comment]
config.ryba.hdfs.namenode_opts was used directly in ryba/hadoop/hdfs_nn. I needed this property because ranger hdfs plugin was not honouring the truststore properties. But it seems that the property has been remove from hdfs install.

ranger.hdfs_plugin.principal is not defined by default as the reba ranger plugin uses the hdfs.krb5_user principal https://github.com/ryba-io/ryba/blame/master/ranger/plugins/hdfs/configure.coffee.md#L43

**Comment by wdavidw** [comment]
> config.ryba.hdfs.namenode_opts was used directly in ryba/hadoop/hdfs_nn. I needed this property because ranger hdfs plugin was not honouring the truststore properties. But it seems that the property has been remove from hdfs install.

So what should we do, remove it completly since it's has been removed probably a few weeks if not a fews month ago and noone noticed it ?

**Comment by wdavidw** [comment]
> ranger.hdfs_plugin.principal is not defined by default as the reba ranger plugin uses the hdfs.krb5_user principal https://github.com/ryba-io/ryba/blame/master/ranger/plugins/hdfs/configure.coffee.md#L43

Again, what should we do. By the way, 3 things that should have been done: a comment inside "setup", a section inside "configure" with an exemple, a section inside 'ryba-env-metal' as well with commented exemple (optional).

**Comment by wdavidw** [comment]
by the way, thanks for answering, It must be pretty late!

**Comment by lucasbak** [comment]
yep you can remove it as we did not notice it was missing.

**Comment by wdavidw** [comment]
OK, what about the second question ?

**Comment by lucasbak** [comment]
concerning the principal, it is opened:
- use directly the hdfs.krb5_user and remove the property hdfs_plugin.principal
- let hdfs_plugin.principal, set the default value based on hdfs.krb5_user to allow a more fine grained policy in case administrators want to have a specific principal for plugins.
